### PR TITLE
Separate Vis from vue2vis

### PR DESCRIPTION
**Pull request by Menighin**
Hi @alexcode ,

I don't know what you think about this idea, but this pull request is to separate Vis totally from the Vue component.
This way, vue2vis will no longer be shipped with Vis and the user of the component will have to install Vis by himself and pass it as prop to the vue component.
This has the advantage of letting the user free to choose which version of Vis he wants to work with and also this kinda removes our responsability to bundle and ship vis together with the wrapper.

I did some testing and it seems to be working fine, but please when you have time do some testing yourself as well.

Let me know what you think,

Best regards

### CODE REVIEW

**Comment by alexcode** [comment]
Hi @Menighin, sorry for the late response but I was in holidays ;)

Regarding this request, I don't really understand why you would to not import visjs by default as vue2vis cannot live without it. 
However, I do agree that visjs should be move to devDependencies (it's something I had plan to do).
Let me know what you think.

Thanks

**Comment by Menighin** [comment]
Hi @alexcode, hope you had good holidays :D

The main (and maybe only) reason to separate vis from the component is to allow the user to use whichever version of Vis he wants to. And also it removes our responsability to build and bundle Vis together, since this seems to be having some weird problems as reported on #5 ...

I'm not so acknowledge about these node modules details, but I just read there's a thing called `peerDependency` that maybe makes more sense... 

What you think about all this? Im kinda in the dark about this n_n'

**Comment by alexcode** [comment]
@Menighin, after thinking an discussing about this, it seems the right to keep `vis` as a dependency as `vue2vis` could not work without it.
I'm reluctant to move it in the `peerDependencies` as it will not install `vis` automatically and only display a warning.

However, I'm also adding the CSS and images to the package in order to fix #5.

**Comment by Menighin** [comment]
Sure! Your point does make sense! =)

**Pull request closed without merging**
